# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql
  encoding: unicode
  pool: 5
  timeout: 5000
development:
  adapter: mysql
  database: user_development
  username: root
  password: root
  host: localhost
test:
  adapter: mysql
  database: user_test
  username: root
  password: root
  host: localhost
production:
  adapter: mysql
  database: user_development
  username: root
  password: root
  host: localhost
