# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
development:
  adapter: postgresql
  encoding: unicode
  database: myapp_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  pool: 5

production:
  adapter: postgresql
  database: user_development

ruby "2.1.1"