default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
development:
  adapter: postgresql
  encoding: unicode
  database: myapp_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  pool: 5

production:
  adapter: postgresql
  database: user_development